### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by getled** [getled/getled#26]
![package-lock-json](https://user-images.githubusercontent.com/34572099/41361278-8a681f64-6f26-11e8-8ed9-4276748294f4.PNG)

**Comment by shramee** [comment]
@getled Could you share the links to both pages..?

**Comment by getled** [comment]
this comes up in gh when signing into the dashboard.

**Comment by shramee** [comment]
Hi Ashley @getled,

It shouldn't be a problem coz we are only using it for development (compiling SCSS). And not on the server...

If we really want to fix it... Please copy paste the content (and possibly screenshot as well) of page that shows up after clicking `Review vulnerable dependency` button.

**Comment by getled** [comment]
sure no problem. Lets leave it then.
