### ISSUE TITLE
Color picker product page issue

### ISSUE THREAD

**Issue by getled** [getled/getled#30]
Color picker only works when selecting a size first. Is this something to do with the backend or a bug?

![colour-problem](https://user-images.githubusercontent.com/34572099/41455668-cfa22aca-7075-11e8-90dd-28d030a35f7e.gif)

**Comment by shramee** [comment]
Not sure why this is happening... Probably designed to work like this..?
To only show relevant images after both (all) attributes have been selected...

**Comment by shramee** [comment]
Lemme know what you think...

**Comment by getled** [comment]
It wasn't working like this before. It used to work fine.

**Comment by getled** [comment]
Using JS Auto select fist size.

**Comment by getled** [comment]
this still doesn't work, for me.
