### ISSUE TITLE
Display Product variation on Category / Product page

### ISSUE THREAD

**Issue by getled** [getled/getled#36]
Let the Admin decide in the customizer whether or not to have the product show all variations for color.

**Comment by shramee** [comment]
Hi Ashley... Looks like this will be quite a bit of work...
Should be a lot easier to just buy the plugin I think... 😓

**Comment by getled** [comment]
This is a very important update to us, which plugin do you recommend, how much work?

**Comment by getled** [comment]
Gone with a plugin for this.
