### ISSUE TITLE
For Safari browser - When selecting Size, no bg colour shows when selecting.

### ISSUE THREAD

**Issue by getled** [getled/getled#60]
It is clearly selecting the right item but not selection colour shows. Also, an issue when trying to select the colour "White". It doesn't really show up but when selected (if known to be there) it is seen.

**Comment by shramee** [comment]
Hi Ahley... Not able to reproduce this... Which version of Safari does this happen on..?

**Comment by getled** [comment]
Hi Shramee, Version 9.9.1
